### ISSUE TITLE
FileNotFoundError: [Errno 2] resulting in no Yaml nor image being pushed to webui output

### ISSUE THREAD

**Issue by MarcusMcNut** [hlky/stable-diffusion#136]
I've been getting this error with both img2img, and txt2img, but I don't always seem to get it, and I'm not quite sure what is happening.  Often when this error happens with img2img I get no results at all, when it happens with txt2img, I get the image in my output folder, but no yaml, and the result isn't shown in the webui output.  I just updated this morning from the stable branch.

`Traceback (most recent call last):
  File "C:\Users\theha\.conda\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\theha\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\Users\theha\.conda\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\theha\.conda\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\theha\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\theha\.conda\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 926, in txt2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 826, in process_images
    save_sample(image, sample_path_i, filename, jpg_sample, prompts, seeds, width, height, steps, cfg_scale,
  File "scripts/webui.py", line 553, in save_sample
    with open(f"{filename_i}.yaml", "w", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/txt2img-samples\\samples\\a_beautiful_furry_fox-goddess_standing_in_front_of_a_portal_to_the_astral_plane.__by_James_Gurney_and_Greg_Rutowski.__Trending_o\\00001-50_k_euler_a_2544649136.yaml'`

**Comment by hlky** [comment]
This will be something to do with the per prompt sample name folder being wrong, if it's only happening on some prompts would you mind sharing some examples of prompts that it has and hasn't happened for? There's probably a mismatch in characters that are removed somewhere

**Comment by MarcusMcNut** [comment]
Sure.  Oh hmm.  Could it be the use of periods on the prompt.  I'll test that also here in a moment.  
For one it was a beautiful goddess standing in front of a portal to the astral 
 plane.  by James Gurney and Greg Rutowski. Trending on Artstation.


I just noticed something this error seems to only occurs when I have the checkbox checked for "Fix faces using GFPGAN"
I'll try fixing a face in the GFPGAN tab and see what happens.

**Comment by hlky** [comment]
I can't reproduce this at all with that prompt, sorry. It's probably just fixed.
