### ISSUE TITLE
img2img broken due to goBIG error (not involving optimized mode)

### ISSUE THREAD

**Issue by JoshuaKimsey** [hlky/stable-diffusion#53]
Started getting this error after updating a few minutes ago, currently running on Linux. I even deleted my setup and rebuilt it, didn't enable optimized mode, and this gets triggered when trying to do anything with img2img:

```bash
Traceback (most recent call last):
  File "/home/JKimsey/anaconda3/envs/lsd/lib/python3.8/site-packages/gradio/routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "/home/JKimsey/anaconda3/envs/lsd/lib/python3.8/site-packages/gradio/blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "/home/JKimsey/anaconda3/envs/lsd/lib/python3.8/site-packages/gradio/blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/JKimsey/anaconda3/envs/lsd/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/JKimsey/anaconda3/envs/lsd/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/JKimsey/anaconda3/envs/lsd/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1428, in img2img
    output_images, seed, info, stats = process_images(
TypeError: process_images() missing 2 required positional arguments: 'gobig_strength' and 'gobig_steps'
```

**Comment by hlky** [comment]
Feature was removed for now,  keep checking wiki, it's being updated with planned new features including GoBIG and other upscalers
