### ISSUE TITLE
img2img crahes every time

### ISSUE THREAD

**Issue by TwistedFromArma** [hlky/stable-diffusion#61]
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\ldo\lib\site-packages\gradio\routes.py", line 247, in run_predict
    output = await app.blocks.process_api(
  File "C:\ProgramData\Miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 641, in process_api
    predictions, duration = await self.call_function(fn_index, processed_input)
  File "C:\ProgramData\Miniconda3\envs\ldo\lib\site-packages\gradio\blocks.py", line 556, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\ProgramData\Miniconda3\envs\ldo\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\ProgramData\Miniconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\ProgramData\Miniconda3\envs\ldo\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "scripts/webui.py", line 1131, in img2img
    output_images, seed, info, stats = process_images(
  File "scripts/webui.py", line 658, in process_images
    assert prompt is not None
AssertionError

**Comment by hlky** [comment]
```
assert prompt is not None
AssertionError
```

You dont have a prompt set.

also, please pay attention to the information on the readme, you havent stated whether this issue is with the stable version in this repo or the development version.

In addition you haven't provided any information on how I can reproduce this, I need to see what you're trying to do. 

Closing this, make the issue again on the dev repo if it's from the development version, make it again here if it's on the stable version, and update both beforehand then try again, and don't forget to provide all the information. There should be templates for bug reports.

**Comment by TwistedFromArma** [comment]
firstly, thank you for a very accessible way to use stable diffusion.

2ndly, as i have demonstrated it is not unfortunately retard proof as claimed.

**Comment by hlky** [comment]
Honestly I don't know why this issue happened to begin with, there should be a default prompt used if you don't enter any input yourself

It's possible you just updated at a bad time when something was broken, we do try to keep the main repo with a stable version working at all times

I hope the update fixed your issue

**Comment by TwistedFromArma** [comment]
yes thank you very much. the issue is solved now.
